Algoritmo "Função SE Alinhada"
//
//
//
// Descrição   : Entendendo a função SE
// Autor(a)    : Thomas
// Data atual  : 09/11/2025
Var
// Seção de Declarações das variáveis

idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreva("DIGITE SUA IDADE: ")
leia(idade)
se((idade>17) e (idade<61)) entao
 escreva ("Adulto")
senao
 se((idade <17)) entao
  escreva ("Criança")
 senao
  escreva ("Idoso")
 fimse
fimse

Fimalgoritmo