Algoritmo "Função PARA aninhado"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/11/2025
Var
// Seção de Declarações das variáveis 

i, j: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

 para i de 1 ate 10 faca
  escreval ("valor de I: ", i)
  para j de 1 ate 3 faca
   escreval("valor de J: ", j)
   fimpara
 fimpara

Fimalgoritmo